---
http_interactions:
- request:
    method: delete
    uri: https://api.opentok.com/v2/project/123456/render/80abaf0d-25a3-4efc-968f-6268d620668d
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - OpenTok-Ruby-SDK/<%= version %>
      X-Opentok-Auth:
      - eyJpc3QiOiJwcm9qZWN0IiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiIxMjM0NTYiLCJpYXQiOjE0OTI1MTA2NjAsImV4cCI6MTQ5MjUxMDk2MH0.BplMVhJWx4ld7KLKXqEmow6MjNPPFw9W8IHCMfeb120
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Thu, 15 Sep 2022 10:51:54 GMT
      Connection:
      - keep-alive
  recorded_at: Tue, 18 Apr 2017 10:17:40 GMT
recorded_with: VCR 6.0.0
